apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes
  namespace: default
  labels:
    web: spring-boot-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-kubernetes
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes
    spec:
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: spring-boot-kubernetes
          image: swr.cn-north-1.myhuaweicloud.com/dennis120338/spring-boot-kubernetes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: testconfig
                  key: host
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/config4
            - name: emptydir
              mountPath: /empty-dir
            - name: dennis
              mountPath: /dennis

      volumes:
        - name: config-volume
          configMap:
            name: testconfig
        - name: emptydir
          emptyDir: {}
        - name: dennis
          hostPath:
            path: /home/yangbin

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: spring-boot-kubernetes
  name: spring-boot-kubernetes
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    app: spring-boot-kubernetes